[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["embedded", "no-std"]
description = "`Î¼fmt` utilities"
documentation = "https://docs.rs/ufmt-utils"
edition = "2018"
keywords = ["Debug", "Display", "Write", "format"]
license = "MIT OR Apache-2.0"
name = "ufmt-utils"
repository = "https://github.com/japaric/ufmt"
version = "0.1.0-alpha.1"

[dependencies]
heapless = "0.5.1"
ufmt-write = { version = "0.1.0-beta.1", path = "../write" }
